# Site wide configuration

title: Emotions
locale: en_US
description: Welcome to emotions webpage. Emotions are the most valuable human nature. They reflect the personality of individual. Emotions sometimes are hidden and sometimes are exposed. The best way to reflect emotions is art. This site is basically "the expression of emotions through a piece of art". This is the site where you can have your brilliant photography, literature and sketch/paintings reflecting emotions get posted and shared. Share the emotions and connect with people.
logo: iStock_000006299889XSmall - emoticons
search: true
url: http://neesha-united.github.io/Emotions


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Your Name
  avatar: bio-photo.jpg
  email: you@email.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
